---
title: "RWorksheet.Sabando#2.Rmd"
author: "Samantha L. Sabando"
date: "2025-09-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r 1}
x<--5:5
x

x<-1:7
x
```
``` {r 2}
B<-seq(1,3,by=0.2)
B
#The output is a numeric vector from 1 to 3 in increments of 0.2.
```
``` {r 3}
ages<-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)
#a
ages[3]
#b
ages[c(2,4)]
#c
ages[-1]
```
``` {r 4}
x<-c("first"=3, "second"=0, "third"=9)
x
#a
x[c("first","third")]

#b output
#first third 
#    3     9 
```
``` {r 5}
x<-3:2
#[1] 3 2
x[2]<-0
x
#[1] 3 0

x[x<-2]
#numeric(0)

#a
#The output is the named vector where the second element "second" has been updated to 0, while the other values remain unchanged.

```
``` {r 6}
month<-c("march","april","may","june","july","august")
price<-c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity<-c(25, 30, 40, 50, 10, 45)
fuel_data<-data.frame(month,price,purchase_quantity)
fuel_data
weighted.mean(price,purchase_quantity)
#b
#The weighted mean shows that Mr. Cruz paid on average ₱59.38 per liter, taking into account the number of liters purchased each month.
```
``` {r 7}
#a summary of statistics
data <- c(
  length(rivers),   # number of rivers
  sum(rivers),      # total length
  mean(rivers),     # average length
  median(rivers),   # median
  var(rivers),      # variance
  sd(rivers),       # standard deviation
  min(rivers),      # minimum
  max(rivers)       # maximum
)
data

#b
#result
[1]  141.000 591114.000  4191.123  4250.000  6111481.000  2472.918  135.000 3710.000
```
``` {r 8}
# Example data (simplified)
celebs <- c("Oprah Winfrey", "Tiger Woods", "J.K. Rowling", "Beyonce", "LeBron James")
power_rank <- c(1, 2, 3, 4, 5)
pay <- c(260, 115, 92, 80, 70)   # in millions $

# Create dataframe
forbes <- data.frame(celebs, power_rank, pay)
forbes

#b
# Change J.K. Rowling’s rank & pay
forbes$power_rank[forbes$celebs == "J.K. Rowling"] <- 15
forbes$pay[forbes$celebs == "J.K. Rowling"] <- 90
forbes
#interpret the data
#Oprah Winfrey remains the most powerful celebrity with the highest pay.
#J.K. Rowling’s ranking dropped to 15, but her pay is still very high ($90M).
#Rankings and pay do not always align perfectly: some celebrities earn a lot but have lower influence (e.g., Rowling), while others may have high influence despite lower pay.
``` 
